question_data = [
    {"text": "The total surface area of a human lung is roughly the size of a tennis court.", "answer": "True"},
    {"text": "In Python, a dictionary can have duplicate keys.", "answer": "False"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Google was originally called BackRub.", "answer": "True"},
    {"text": "Chameleons change color solely to blend in with their surroundings.", "answer": "False"},
    {"text": "Mount Everest is the furthest point from the center of the Earth.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "A cross between a donkey and a zebra is called a 'Zonkey'.", "answer": "True"},
    {"text": "DNA stands for Deoxyribonucleic Acid.", "answer": "True"},
    {"text": "The light year is a unit of time.", "answer": "False"},
    {"text": "A turtle can breathe through its butt.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "The Great Wall of China is clearly visible from space with the naked eye.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Goldfish only have a memory span of three seconds.", "answer": "False"},
    {"text": "The core of the Earth is hotter than the surface of the sun.", "answer": "True"},
    {"text": "There are more cells of bacteria in your body than there are human cells.", "answer": "True"},
    {"text": "Your tastebuds are replaced every 10 to 14 days.", "answer": "True"},
    {"text": "A double-byte character set is required for Arabic.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "If you cry in space, your tears just float around your face.", "answer": "True"},
    {"text": "The emoji was invented in Japan.", "answer": "True"},
    {"text": "Humans share about 50% of their DNA with bananas.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The shortest war in history lasted less than an hour.", "answer": "True"},
    {"text": "A standard deck of cards has 52 cards.", "answer": "True"},
    {"text": "The Declaration of Independence was signed on July 4, 1776.", "answer": "False"},
    {"text": "M&M stands for Mars and Murrie.", "answer": "True"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "Water boils at a lower temperature at higher altitudes.", "answer": "True"},
    {"text": "Every country in the world uses the metric system except the United States.", "answer": "False"},
    {"text": "Cats use their whiskers to check if they can fit through an opening.", "answer": "True"},
    {"text": "The first computer virus was created in the 1980s.", "answer": "True"},
    {"text": "A standard 18-hole golf course has exactly 18 holes.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "The first electronic computer was called ENIAC.", "answer": "True"},
    {"text": "Sound cannot travel through a vacuum.", "answer": "True"},
    {"text": "The planet Venus rotates clockwise.", "answer": "True"},
    {"text": "An hummingbird can fly backward.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "A full-grown lion can weigh up to 500 pounds.", "answer": "True"},
    {"text": "Ice is less dense than liquid water.", "answer": "True"},
    {"text": "The Eiffel Tower can grow taller during the summer.", "answer": "True"},
    {"text": "Cows have four stomachs.", "answer": "False"},
    {"text": "The first iPhone was released in 2005.", "answer": "False"},
    {"text": "Sloths can hold their breath longer than dolphins.", "answer": "True"},
    {"text": "The chemical symbol for silver is Au.", "answer": "False"},
    {"text": "A standard piano has 88 keys.", "answer": "True"},
    {"text": "All internal organs of a shrimp are located in its head.", "answer": "True"},
    {"text": "A standard day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "The capital of New York is New York City.", "answer": "False"},
    {"text": "Hot water freezes faster than cold water under certain conditions.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Albert Einstein failed math in primary school.", "answer": "False"},
    {"text": "Penguins can fly underwater.", "answer": "True"},
    {"text": "An standard sheet of paper can be folded in half more than 7 times.", "answer": "True"},
    {"text": "Tomatoes are vegetables.", "answer": "False"},
    {"text": "The human skeleton renews itself completely every 10 years.", "answer": "True"},
    {"text": "A standard bowling ball has 4 holes.", "answer": "False"},
    {"text": "The currency of Japan is the Yuan.", "answer": "False"},
    {"text": "Ostriches bury their heads in the sand when scared.", "answer": "False"},
    {"text": "The first person to walk on the moon was Neil Armstrong.", "answer": "True"},
    {"text": "A double negative in English always creates a positive.", "answer": "False"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "The heart of a blue whale is the size of a small car.", "answer": "True"},
    {"text": "Napoleon Bonaparte was exceptionally short for his time.", "answer": "False"},
    {"text": "A human brain generates enough electricity to power a small light bulb.", "answer": "True"},
    {"text": "Diamonds are made of highly compressed carbon.", "answer": "True"},
    {"text": "The first commercial video game was Pong.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "The capital of Brazil is Rio de Janeiro.", "answer": "False"},
    {"text": "There are 365 days in a standard calendar year.", "answer": "True"},
    {"text": "Strawberries are not actual berries, but bananas are.", "answer": "True"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "The Statue of Liberty was a gift from France.", "answer": "True"},
    {"text": "Butterflies taste food with their feet.", "answer": "True"},
    {"text": "The first commercial flight took place in 1914.", "answer": "True"},
    {"text": "The human body is made up of approximately 60% water.", "answer": "True"},
    {"text": "The capital of Spain is Madrid.", "answer": "True"},
    {"text": "An adult human has fewer bones than a newborn baby.", "answer": "True"},
    {"text": "The Great Pyramid of Giza is the oldest of the Seven Wonders.", "answer": "True"},
    {"text": "Kangaroos cannot walk backward.", "answer": "True"},
    {"text": "The first programming language was called Fortran.", "answer": "False"},
    {"text": "A standard basketball has 8 panels.", "answer": "True"},
    {"text": "The Pacific Ocean is expanding every year.", "answer": "False"},
    {"text": "The first smart watch was released in the 21st century.", "answer": "False"},
    {"text": "A honeybee can fly at speeds up to 15 miles per hour.", "answer": "True"},
    {"text": "The capital of Germany is Munich.", "answer": "False"},
    {"text": "The human eye can distinguish about 10 million different colors.", "answer": "True"},
    {"text": "The first printed book was the Bible.", "answer": "False"},
    {"text": "A jellyfish is 95% water.", "answer": "True"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The first successful airplane was flown by the Wright brothers.", "answer": "True"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "An ant can lift up to 50 times its own body weight.", "answer": "True"},
    {"text": "The first computer mouse was made of wood.", "answer": "True"},
    {"text": "The total number of keys on a standard computer keyboard is 104.", "answer": "True"},
    {"text": "The sun is a star.", "answer": "True"}
]